### ISSUE TITLE
Allow any codec

### ISSUE THREAD

**Issue by asdine** [heetch/felice#15]
Support any codec for encoding/decoding a message body.
The codec must be specified at the following locations:
- producer:
  - specify the default codec for all produced messages
  - specify a codec for a single message
- consumer:
  - specify the default codec for all consumed messages
  - topic declaration: specify which codec to use when consuming all messages from a specific topic

Specifying a codec must be an obligation, the producer or consumer should not work if no codec of default codec was explicitly specified by the user.

**Comment by tealeg** [comment]
@asdine when we talk about Codec here, are we talking about the codec used inside our `message.New` function (currently hardcoded as JSON) or the sarama encoder used inside `Producer.SendMessage` (currently either `sarama.ByteEncoder` or `sarama.StringEncoder`)?

**Comment by tealeg** [comment]
From sprint planning: we should do this per topic (for consumer).  One codec per key, and per messeage.

**Comment by asdine** [comment]
Fixed by #32
