### ISSUE TITLE
Have a constructor for the Consumer type

### ISSUE THREAD

**Issue by YassineE** [heetch/felice#22]
I think that we should have a constructor for the `Consumer` type because its zero value is not usable.

For example, if I create a consumer like that:
```golang
c := consumer.Consumer{}
```
`c` is not usable because I need to have some fields to be initialized (think of the Logger for example).

Two proposals:
- expose the `setup` method and don't call it from the `Handle` anymore
- add a constructor (`func New(//maybe some params) *Consumer {...}`) and remove the `setup` method

**Comment by tealeg** [comment]
I don't think it's true that it's not usable - the RetryInterval already defaults, and both Logging and Metrics  are optional.

**Comment by YassineE** [comment]
There are optional indeed but if I want to use the Logger for example before calling the `Handle` method (which calls the `setup` one). How can I do?

The use case is for `kafka-go`, I need the `Logger` before any calls to `Handle`.

**Comment by tealeg** [comment]
So you simply initialise the Consumer with the Logger, no?
```
c := &Consumer{Logger: myLogger}
```
.. no?

**Comment by YassineE** [comment]
Yes you are right, I am always wondering when should I use a constructor or not.
