### ISSUE TITLE
Rework Consumer API

### ISSUE THREAD

**Issue by YassineE** [heetch/felice#44]
As @rogpeppe [duly noticed](https://github.com/heetch/felice/pull/42#pullrequestreview-249228767), the actual Consumer's API can lead to several mistakes if it is not configured properly.

The idea is to add a constructor for the Consumer which holds a ready to use configuration, something like the following:
```go
package consumer

func New(cfg *Config) *Consumer {
...
}
```

This is a big breaking changes but as we are still in v0.x.x, it is still the time to break the API.

What do you think guys @rogpeppe @tealeg @asdine?

**Comment by rogpeppe** [comment]
I think this would be worth doing, although I think I'd make this the signature:

    func New(cfg Config) (*Consumer, error)

That way we're free to return an error when the configuration is invalid and we lose the edge case of having a nil config.
