### ISSUE TITLE
Lack of integration tests

### ISSUE THREAD

**Issue by asdine** [heetch/felice#48]
Currently, we are using mocks to test Felice code which means that unless we manually create a main to test the code every time, there's no way to make sure we didn't break anything.

I propose to create a few integration tests protected by a flag, a build tag or whatever that would connect to an actual Kafka instance and test the production and the consumption.
The goal of these tests is solely to test the global behavior.
These tests would be run **on Drone only**

cc @rogpeppe

**Comment by tealeg** [comment]
Fixed by #52
